/**
 * exporter.js — HTML/CSS export + fixed Blogger XML theme generation
 */

const NAV_EXCLUDE = new Set(['footer','alert','badges','newsletter','clients','progress','timeline','counters','accordion','tabs','slider']);

const Exporter = {

  buildSectionsHtml(project) {
    const globalEnabled = !project.siteSettings || project.siteSettings.scrollAnimEnabled !== false;
    return project.sections.filter(s=>s.visible!==false)
      .map(s=>{
        let html=SectionRegistry[s.type].render(s,project);
        if(window.BgEffects) html=BgEffects.injectIntoSectionHtml(html,s);
        return Animations.wrap(html,s.animation,globalEnabled);
      }).join('\n');
  },

  buildSectionsHtmlBloggerSafe(project) {
    const globalEnabled = !project.siteSettings || project.siteSettings.scrollAnimEnabled !== false;
    return project.sections.filter(s=>s.visible!==false)
      .map(s=>{
        // Slider and Counters have inline <script> — use static fallback for Blogger
        if(s.type==='slider'){
          const first=s.items[0];
          if(!first)return '';
          return Animations.wrap(`<section id="${s.id}" class="wb-section wb-slider-section"><div class="wb-slide" style="height:${s.height}px;background-image:linear-gradient(rgba(0,0,0,.4),rgba(0,0,0,.4)),url('${escapeHtml(first.image)}');display:flex;align-items:center;justify-content:center;color:#fff;text-align:center;"><div class="wb-slide-inner"><h2>${escapeHtml(first.heading)}</h2><p>${escapeHtml(first.text)}</p>${first.buttonText?`<a href="${escapeHtml(first.buttonLink)}" class="wb-btn wb-btn-primary">${escapeHtml(first.buttonText)}</a>`:''}</div></div></section>`,s.animation,globalEnabled);
        }
        let html=SectionRegistry[s.type].render(s,project);
        if(window.BgEffects) html=BgEffects.injectIntoSectionHtml(html,s);
        return Animations.wrap(html,s.animation,globalEnabled);
      }).join('\n');
  },

  buildNavbar(project) {
    const menu = project.menu;
    const sectionLabel = (id) => {
      const s = project.sections.find(x => x.id === id);
      if (!s) return '';
      if (s.navLabel) return s.navLabel;
      const def = SectionRegistry[s.type];
      return s.heading || s.companyName || (def ? def.meta.name : '');
    };
    let navItems;
    if (menu && menu.customized && menu.items.length) {
      navItems = menu.items.map(item => {
        if (item.type === 'dropdown') {
          const children = (item.children || []).map(c => {
            const href = c.type === 'section' ? `#${c.sectionId}` : (c.url || '#');
            const label = c.type === 'section' ? sectionLabel(c.sectionId) : c.label;
            return `<a href="${escapeHtml(href)}" class="wb-nav-link">${escapeHtml(label || c.label)}</a>`;
          }).join('');
          return `<div class="wb-nav-dropdown"><span class="wb-nav-link wb-nav-dropdown-trigger">${escapeHtml(item.label)} ▾</span><div class="wb-nav-dropdown-menu">${children}</div></div>`;
        }
        const href = item.type === 'section' ? `#${item.sectionId}` : (item.url || '#');
        return `<a href="${escapeHtml(href)}" class="wb-nav-link">${escapeHtml(item.label)}</a>`;
      }).join('');
    } else {
      navItems = project.sections
        .filter(s => s.visible !== false && !NAV_EXCLUDE.has(s.type))
        .map(s => `<a href="#${s.id}" class="wb-nav-link">${escapeHtml(sectionLabel(s.id))}</a>`).join('');
    }
    const navClasses = ['wb-navbar'];
    if (menu && menu.sticky === false) navClasses.push('wb-navbar-static');
    if (menu && menu.transparent) navClasses.push('wb-navbar-transparent');
    return `<nav class="${navClasses.join(' ')}" id="wb-navbar"><div class="wb-container wb-navbar-inner"><a href="#" class="wb-navbar-brand">${escapeHtml(project.meta.title)}</a><button class="wb-navbar-toggle" id="wb-navbar-toggle" aria-label="Toggle menu">&#9776;</button><div class="wb-navbar-links" id="wb-navbar-links">${navItems}</div></div></nav>`.trim();
  },

  buildBaseCss(project) {
    const t=project.theme;
    const fontFaces=(t.localFonts||[]).map(f=>`@font-face{font-family:'${f.name}';src:url('${f.dataUrl}') format('${f.format}');font-display:swap;}`).join('\n');
    return `/* Generated by Offline Website Builder Pro */
${fontFaces}
:root{--wb-primary:${t.primary};--wb-secondary:${t.secondary};--wb-accent:${t.accent};--wb-bg:${t.background};--wb-surface:${t.surface};--wb-text:${t.text};--wb-font-heading:'${t.fontHeading}',sans-serif;--wb-font-body:'${t.fontBody}',sans-serif;}
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:var(--wb-font-body);color:var(--wb-text);background:var(--wb-bg);line-height:1.6;scroll-behavior:smooth;}
h1,h2,h3,h4{font-family:var(--wb-font-heading);line-height:1.2;margin-bottom:.5em;}
img{max-width:100%;display:block;}
a{text-decoration:none;color:inherit;}
.wb-container{max-width:var(--wb-container,1140px);margin:0 auto;padding:0 24px;}
.wb-section{width:100%;}
.wb-btn{display:inline-block;padding:14px 32px;border-radius:var(--wb-radius,8px);font-weight:600;transition:transform .15s ease,opacity .15s ease;}
.wb-btn:hover{transform:translateY(-2px);opacity:.92;}
.wb-btn-primary{background:var(--wb-primary);color:#fff;}
.wb-btn-light{background:#fff;color:var(--wb-secondary);}
.wb-align-center .wb-container{margin:0 auto;text-align:center;}
.wb-align-left .wb-container{text-align:left;}
.wb-align-right .wb-container{text-align:right;}
.wb-hero-inner{max-width:760px;}
.wb-align-center .wb-hero-inner{margin:0 auto;}
.wb-hero-heading{font-size:clamp(2rem,5vw,3.25rem);margin-bottom:20px;}
.wb-hero-subheading{font-size:1.15rem;opacity:.9;margin-bottom:32px;}
.wb-about-grid{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center;padding:80px 24px;}
.wb-about-grid.wb-reverse{direction:rtl;}
.wb-about-grid.wb-reverse>*{direction:ltr;}
.wb-about-image img{border-radius:16px;}
.wb-eyebrow{display:inline-block;color:var(--wb-primary);font-weight:700;letter-spacing:.05em;text-transform:uppercase;font-size:.8rem;margin-bottom:12px;}
.wb-about-text h2{font-size:2rem;}
.wb-section-head{text-align:center;max-width:600px;margin:0 auto 48px;}
.wb-section-head h2{font-size:2rem;}
.wb-section-head p{opacity:.75;}
.wb-grid{display:grid;gap:28px;}
.wb-grid-3{grid-template-columns:repeat(3,1fr);}
.wb-grid-2{grid-template-columns:repeat(2,1fr);}
.wb-card{padding:36px 28px;border-radius:var(--wb-radius,14px);box-shadow:0 4px 24px rgba(0,0,0,.06);}
.wb-card-icon{font-size:2.25rem;margin-bottom:16px;}
.wb-testimonial{padding:32px;border-radius:var(--wb-radius,14px);}
.wb-quote{font-size:1.05rem;margin-bottom:20px;opacity:.92;}
.wb-testimonial-author{display:flex;align-items:center;gap:14px;}
.wb-avatar{width:48px;height:48px;border-radius:50%;object-fit:cover;}
.wb-avatar-placeholder{display:flex;align-items:center;justify-content:center;background:var(--wb-primary);color:#fff;font-weight:700;}
.wb-testimonial-author div{display:flex;flex-direction:column;}
.wb-testimonial-author span{font-size:.85rem;opacity:.7;}
.wb-cta-inner{text-align:center;max-width:640px;margin:0 auto;}
.wb-cta h2{font-size:1.85rem;}
.wb-cta p{margin-bottom:28px;opacity:.92;}
.wb-footer-grid{display:grid;grid-template-columns:1fr 1fr;gap:32px;padding-bottom:40px;}
.wb-footer-brand{color:#fff;font-size:1.4rem;margin-bottom:12px;}
.wb-social-row{display:flex;gap:10px;margin-top:20px;}
.wb-social-link{width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,.1);display:inline-flex;align-items:center;justify-content:center;font-weight:700;}
.wb-footer-contact p{margin-bottom:8px;opacity:.85;}
.wb-footer-bottom{text-align:center;padding:20px 0;border-top:1px solid rgba(255,255,255,.1);font-size:.85rem;opacity:.7;}
.wb-navbar{position:sticky;top:0;z-index:100;background:rgba(255,255,255,.95);backdrop-filter:blur(8px);box-shadow:0 1px 0 rgba(0,0,0,.06);}
.wb-navbar-inner{display:flex;align-items:center;justify-content:space-between;height:68px;}
.wb-navbar-brand{font-weight:700;font-size:1.15rem;}
.wb-navbar-links{display:flex;gap:28px;}
.wb-nav-link{font-weight:500;font-size:.95rem;}
.wb-nav-link.active{color:var(--wb-primary);}
.wb-navbar-toggle{display:none;background:none;border:none;font-size:1.4rem;cursor:pointer;}
.wb-navbar-static{position:static;}
.wb-navbar-transparent{position:absolute;top:0;left:0;right:0;background:transparent;box-shadow:none;backdrop-filter:none;}
.wb-navbar-transparent .wb-nav-link,.wb-navbar-transparent .wb-navbar-brand{color:#fff;}
.wb-nav-dropdown{position:relative;display:inline-block;}
.wb-nav-dropdown-trigger{cursor:pointer;}
.wb-nav-dropdown-menu{position:absolute;top:100%;left:0;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,.12);border-radius:var(--wb-radius,8px);padding:8px;min-width:160px;display:none;flex-direction:column;z-index:200;}
.wb-nav-dropdown-menu .wb-nav-link{color:#111 !important;padding:8px 10px;display:block;}
.wb-nav-dropdown:hover .wb-nav-dropdown-menu{display:flex;}
.wb-faq-item{border:1px solid rgba(0,0,0,.08);border-radius:var(--wb-radius,10px);padding:18px 20px;margin-bottom:12px;}
.wb-faq-question{cursor:pointer;font-weight:600;list-style:none;}
.wb-faq-question::-webkit-details-marker{display:none;}
.wb-faq-answer{margin-top:12px;opacity:.8;line-height:1.7;}
.wb-faq-container{max-width:760px;margin:0 auto;}
.wb-gallery-grid{display:grid;gap:16px;grid-template-columns:repeat(4,1fr);}
.wb-gallery-item{position:relative;display:block;border-radius:10px;overflow:hidden;aspect-ratio:1/1;}
.wb-gallery-item img{width:100%;height:100%;object-fit:cover;transition:transform .3s ease;}
.wb-gallery-item:hover img{transform:scale(1.06);}
.wb-gallery-caption{position:absolute;left:0;right:0;bottom:0;padding:10px;background:linear-gradient(transparent,rgba(0,0,0,.65));color:#fff;font-size:.82rem;}
.wb-lightbox{position:fixed;inset:0;background:rgba(0,0,0,.92);display:flex;align-items:center;justify-content:center;opacity:0;visibility:hidden;transition:opacity .2s ease;z-index:1000;}
.wb-lightbox:target{opacity:1;visibility:visible;}
.wb-lightbox img{max-width:90vw;max-height:85vh;border-radius:8px;}
.wb-lightbox-close{position:absolute;top:24px;right:32px;color:#fff;font-size:2.2rem;line-height:1;}
.wb-slider-section{position:relative;}
.wb-slider{position:relative;overflow:hidden;}
.wb-slider-track{display:flex;height:100%;transition:transform .5s ease;}
.wb-slide{flex:0 0 100%;height:100%;display:flex;align-items:center;justify-content:center;background-size:cover;background-position:center;color:#fff;text-align:center;}
.wb-slide-inner{max-width:680px;padding:0 24px;}
.wb-slide-inner h2{font-size:clamp(1.8rem,4vw,2.8rem);margin-bottom:16px;}
.wb-slide-inner p{font-size:1.05rem;opacity:.92;margin-bottom:24px;}
.wb-slider-arrow{position:absolute;top:50%;transform:translateY(-50%);z-index:5;width:44px;height:44px;border-radius:50%;border:none;cursor:pointer;background:rgba(255,255,255,.25);color:#fff;font-size:1.6rem;display:flex;align-items:center;justify-content:center;}
.wb-slider-prev{left:20px;}
.wb-slider-next{right:20px;}
.wb-slider-dots{position:absolute;bottom:20px;left:0;right:0;display:flex;justify-content:center;gap:8px;z-index:5;}
.wb-slider-dot{width:10px;height:10px;border-radius:50%;border:none;background:rgba(255,255,255,.5);cursor:pointer;padding:0;transition:width .2s ease,border-radius .2s ease;}
.wb-slider-dot.active{background:#fff;width:26px;border-radius:6px;}
.wb-video-frame{position:relative;max-width:880px;margin:0 auto;aspect-ratio:16/9;border-radius:var(--wb-radius,14px);overflow:hidden;background:#000;}
.wb-video-frame iframe,.wb-video-frame video{width:100%;height:100%;border:none;display:block;}
.wb-blog-card{display:block;border-radius:var(--wb-radius,14px);overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.06);}
.wb-blog-card img{width:100%;height:190px;object-fit:cover;}
.wb-blog-body{padding:22px;}
.wb-blog-date{font-size:.78rem;opacity:.55;text-transform:uppercase;letter-spacing:.04em;}
.wb-blog-body h3{font-size:1.15rem;margin:8px 0;}
.wb-blog-body p{font-size:.9rem;opacity:.75;}
.wb-stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:32px;text-align:center;}
.wb-stat-number{font-size:2.8rem;font-weight:900;letter-spacing:-.02em;line-height:1;margin-bottom:10px;}
.wb-stat-label{font-size:.9rem;opacity:.7;font-weight:500;}
.wb-clients-track{display:flex;gap:48px;align-items:center;overflow-x:auto;}
.wb-clients-autoplay{overflow:hidden;width:max-content;animation:wb-marquee 22s linear infinite;}
.wb-clients-autoplay:hover{animation-play-state:paused;}
@keyframes wb-marquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}
.wb-client-logo{flex-shrink:0;height:48px;display:flex;align-items:center;opacity:.7;filter:grayscale(1);}
.wb-client-logo img{height:100%;object-fit:contain;}
.wb-client-logo span{font-weight:700;font-size:1.1rem;white-space:nowrap;}
.wb-map-embed{width:100%;overflow:hidden;}
.wb-map-embed iframe{display:block;width:100%;height:100%;border:0;}
.wb-map-frame{margin-top:20px;border-radius:var(--wb-radius,12px);overflow:hidden;aspect-ratio:16/10;}
.wb-map-frame iframe{width:100%;height:100%;border:0;}
.wb-contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:48px;}
.wb-contact-list{list-style:none;margin:20px 0;display:flex;flex-direction:column;gap:10px;opacity:.85;}
.wb-contact-form{display:flex;flex-direction:column;gap:14px;}
.wb-contact-form input,.wb-contact-form textarea{padding:14px 16px;border-radius:8px;border:1px solid rgba(0,0,0,.12);font-family:inherit;font-size:.95rem;resize:vertical;}
.wb-contact-form button{align-self:flex-start;border:none;cursor:pointer;}
.wb-newsletter-inner{text-align:center;max-width:560px;margin:0 auto;}
.wb-newsletter-form{display:flex;gap:10px;margin-top:24px;}
.wb-newsletter-form input{flex:1;padding:14px 16px;border-radius:8px;border:none;font-size:.95rem;}
.wb-newsletter-form button{border:none;cursor:pointer;white-space:nowrap;}
.wb-pricing-grid{align-items:stretch;}
.wb-pricing-card{padding:36px 28px;border-radius:var(--wb-radius,14px);border:2px solid transparent;display:flex;flex-direction:column;gap:14px;}
.wb-pricing-highlight{transform:scale(1.03);box-shadow:0 12px 40px rgba(0,0,0,.12);}
.wb-pricing-price{font-size:2.2rem;font-weight:800;}
.wb-pricing-period{font-size:.8rem;opacity:.6;margin-top:-10px;}
.wb-pricing-features{list-style:none;flex:1;display:flex;flex-direction:column;gap:10px;margin:8px 0;}
.wb-pricing-features li{padding-left:22px;position:relative;font-size:.92rem;opacity:.85;}
.wb-pricing-features li::before{content:'\\2713';position:absolute;left:0;color:var(--wb-primary);font-weight:700;}
.wb-team-card{text-align:center;}
.wb-team-photo{width:140px;height:140px;border-radius:50%;object-fit:cover;margin:0 auto 18px;}
.wb-team-role{opacity:.65;font-size:.9rem;margin-bottom:12px;}
.wb-tabs-radio{position:absolute;opacity:0;pointer-events:none;}
.wb-tabs-labels{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-bottom:32px;}
.wb-tabs-label{padding:10px 22px;border-radius:24px;background:rgba(0,0,0,.05);cursor:pointer;font-weight:600;font-size:.9rem;}
.wb-tabs-panel{display:none;max-width:700px;margin:0 auto;text-align:center;font-size:1.02rem;opacity:.85;line-height:1.7;}
.wb-tabs-radio:nth-of-type(1):checked~.wb-tabs-labels .wb-tabs-label:nth-of-type(1),.wb-tabs-radio:nth-of-type(2):checked~.wb-tabs-labels .wb-tabs-label:nth-of-type(2),.wb-tabs-radio:nth-of-type(3):checked~.wb-tabs-labels .wb-tabs-label:nth-of-type(3){background:var(--wb-primary);color:#fff;}
.wb-tabs-radio:nth-of-type(1):checked~.wb-tabs-panels .wb-tabs-panel:nth-of-type(1),.wb-tabs-radio:nth-of-type(2):checked~.wb-tabs-panels .wb-tabs-panel:nth-of-type(2),.wb-tabs-radio:nth-of-type(3):checked~.wb-tabs-panels .wb-tabs-panel:nth-of-type(3){display:block;}
.wb-timeline{position:relative;max-width:680px;margin:0 auto;padding-left:32px;border-left:2px solid rgba(0,0,0,.1);}
.wb-timeline-item{position:relative;padding-bottom:36px;}
.wb-timeline-dot{position:absolute;left:-39px;top:4px;width:14px;height:14px;border-radius:50%;}
.wb-timeline-date{font-weight:700;font-size:.85rem;text-transform:uppercase;letter-spacing:.04em;}
.wb-timeline-content h3{margin:6px 0;font-size:1.15rem;}
.wb-timeline-content p{opacity:.75;}
.wb-counters-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:32px;text-align:center;}
.wb-counter-number{font-size:2.6rem;font-weight:800;}
.wb-counter-label{opacity:.8;margin-top:6px;font-size:.92rem;}
.wb-progress-container{max-width:680px;margin:0 auto;}
.wb-progress-item{margin-bottom:22px;}
.wb-progress-label{display:flex;justify-content:space-between;font-size:.9rem;font-weight:600;margin-bottom:8px;}
.wb-progress-track{height:10px;border-radius:6px;background:rgba(0,0,0,.08);overflow:hidden;}
.wb-progress-fill{height:100%;border-radius:6px;}
.wb-badges-row{display:flex;gap:10px;flex-wrap:wrap;justify-content:center;}
.wb-badge{padding:8px 16px;border-radius:20px;font-size:.85rem;font-weight:600;border:1px solid;}
.wb-alert{position:relative;padding:14px 0;font-size:.92rem;}
.wb-alert-inner{display:flex;align-items:center;justify-content:center;gap:14px;flex-wrap:wrap;text-align:center;}
.wb-alert-info{background:#eff6ff;color:#1e40af;}
.wb-alert-success{background:#f0fdf4;color:#15803d;}
.wb-alert-warning{background:#fffbeb;color:#b45309;}
.wb-alert-error{background:#fef2f2;color:#b91c1c;}
.wb-alert-link{font-weight:700;text-decoration:underline;}
.wb-alert-dismiss-toggle{position:absolute;opacity:0;pointer-events:none;}
.wb-alert-close{position:absolute;right:20px;top:50%;transform:translateY(-50%);cursor:pointer;font-size:1.3rem;}
.wb-alert:has(.wb-alert-dismiss-toggle:checked){display:none;}
.wb-cgrid{display:grid;gap:24px;}
.wb-citem{background:var(--wb-surface);border-radius:var(--wb-radius,14px);overflow:hidden;}
.wb-citem img{width:100%;height:190px;object-fit:cover;display:block;background:#ddd;}
.wb-citem .wb-cbody{padding:22px;}
.wb-citem h4{font-size:1.1rem;margin-bottom:8px;}
.wb-citem p{font-size:.9rem;opacity:.75;}
.wb-cgrid-empty,.wb-form-empty,.wb-bloglist-empty{opacity:.6;font-size:.9rem;padding:24px;border:1px dashed currentColor;border-radius:var(--wb-radius,10px);text-align:center;}
.wbform{max-width:520px;}
.wbform .wb-frow{margin-bottom:16px;}
.wbform label{display:block;font-size:.9rem;font-weight:600;margin-bottom:6px;}
.wbform input[type=text],.wbform input[type=email],.wbform input[type=tel],.wbform input[type=number],
.wbform input[type=date],.wbform input[type=time],.wbform textarea,.wbform select{
  width:100%;padding:12px 14px;border:1px solid rgba(0,0,0,.15);border-radius:var(--wb-radius,8px);font-size:.95rem;font-family:inherit;background:#fff;color:#111;
}
.wbform .radio-opt,.wbform .check-opt{display:flex;align-items:center;gap:8px;font-weight:400;font-size:.92rem;margin-bottom:6px;}
.wb-blog-cards{display:grid;gap:24px;}
.wb-float-widgets{position:fixed;right:20px;bottom:20px;display:flex;flex-direction:column;gap:12px;z-index:999;}
.wb-float-btn{width:56px;height:56px;border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,.25);font-size:1.6rem;text-decoration:none;color:#fff !important;border:none;cursor:pointer;}
.wb-float-whatsapp{background:#25d366;}
.wb-float-call{background:var(--wb-primary);}
.wb-float-backtotop{background:var(--wb-secondary);opacity:0;pointer-events:none;transition:opacity .2s ease;}
.wb-float-backtotop.wb-show{opacity:1;pointer-events:auto;}
.wb-popup-toggle{display:none;}
.wb-popup-overlay,.wb-popup-box{display:none;}
.wb-popup-toggle:checked ~ .wb-popup-overlay,.wb-popup-toggle:checked ~ .wb-popup-box{display:block;}
.wb-popup-overlay{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:1000;cursor:default;}
.wb-popup-box{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:1001;max-width:480px;width:calc(100% - 40px);max-height:calc(100vh - 60px);overflow-y:auto;border-radius:var(--wb-radius,14px);padding:36px 32px;box-shadow:0 20px 60px rgba(0,0,0,.3);text-align:left;}
.wb-popup-trigger{cursor:pointer;}
.wb-popup-close{position:absolute;top:14px;right:18px;cursor:pointer;font-size:1.5rem;line-height:1;opacity:.55;}
.wb-popup-close:hover{opacity:1;}
.wb-popup-image{width:100%;height:180px;object-fit:cover;border-radius:calc(var(--wb-radius, 14px) - 4px);margin-bottom:18px;}
.wb-popup-heading{font-size:1.4rem;margin-bottom:12px;padding-right:24px;}
.wb-popup-body{font-size:.95rem;opacity:.85;line-height:1.6;margin-bottom:6px;}
.wb-popup-cta{display:inline-block;margin-top:6px;}
.wb-iframe-wrap{width:100%;border-radius:var(--wb-radius,10px);overflow:hidden;}
.wb-iframe-wrap iframe{width:100%;height:100%;border:0;display:block;}
.wb-iframe-empty,.wb-custom-html-empty{display:flex;align-items:center;justify-content:center;text-align:center;opacity:.55;font-size:.9rem;border:1px dashed currentColor;border-radius:var(--wb-radius,10px);padding:20px;}
${Animations.buildCss()}
${window.BgEffects ? BgEffects.buildCss() : ''}
@media(max-width:820px){
  .wb-about-grid,.wb-footer-grid,.wb-contact-grid{grid-template-columns:1fr;}
  .wb-grid-3,.wb-grid-2{grid-template-columns:1fr;}
  .wb-gallery-grid{grid-template-columns:repeat(2,1fr);}
  .wb-stats-grid{grid-template-columns:repeat(2,1fr);}
  .wb-pricing-highlight{transform:none;}
  .wb-newsletter-form{flex-direction:column;}
  .wb-navbar-toggle{display:block;}
  .wb-navbar-links{position:absolute;top:68px;left:0;right:0;background:#fff;flex-direction:column;padding:16px 24px;display:none;}
  .wb-navbar-links.open{display:flex;}
  .wb-cgrid,.wb-blog-cards{grid-template-columns:1fr !important;}
}`;
  },

  /**
   * scopeCss — prefixes every top-level selector in `css` with `scope` so the exported
   * site's global styles (body{...}, h1,h2{...}, .wb-btn{...}, etc.) can be safely injected
   * live into the editor canvas without leaking out and overriding the builder chrome's own
   * dark UI. @media/@supports are recursed into; @keyframes and @font-face pass through untouched.
   */
  scopeCss(css, scope) {
    const keyframes = [];
    css = css.replace(/@keyframes\s+[\w-]+\s*\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}/g, (m) => {
      keyframes.push(m);
      return `\u0000KF${keyframes.length - 1}\u0000`;
    });
    let out = '';
    let i = 0;
    const n = css.length;
    while (i < n) {
      while (i < n && /\s/.test(css[i])) i++;
      if (i >= n) break;
      if (css[i] === '\u0000') {
        const end = css.indexOf('\u0000', i + 1);
        out += css.slice(i, end + 1) + '\n';
        i = end + 1;
        continue;
      }
      const braceIdx = css.indexOf('{', i);
      if (braceIdx === -1) { out += css.slice(i); break; }
      const header = css.slice(i, braceIdx).trim();
      if (header.startsWith('@media') || header.startsWith('@supports')) {
        let depth = 0, j = braceIdx;
        for (; j < n; j++) {
          if (css[j] === '{') depth++;
          else if (css[j] === '}') { depth--; if (depth === 0) break; }
        }
        const inner = css.slice(braceIdx + 1, j);
        out += header + '{' + this.scopeCss(inner, scope) + '}\n';
        i = j + 1;
      } else if (header.startsWith('@font-face') || header.startsWith('@page') || header.startsWith('@import')) {
        const closeIdx = css.indexOf('}', braceIdx);
        out += css.slice(i, closeIdx + 1) + '\n';
        i = closeIdx + 1;
      } else {
        const closeIdx = css.indexOf('}', braceIdx);
        const body = css.slice(braceIdx + 1, closeIdx);
        const scoped = header.split(',').map(sel => {
          sel = sel.trim();
          if (!sel) return sel;
          return `${scope} ${sel}`;
        }).join(', ');
        out += scoped + '{' + body + '}\n';
        i = closeIdx + 1;
      }
    }
    return out.replace(/\u0000KF(\d+)\u0000/g, (_, idx) => keyframes[+idx]);
  },

  buildBaseJs() {
    return `// Generated by Offline Website Builder Pro
(function(){
var toggle=document.getElementById('wb-navbar-toggle');
var links=document.getElementById('wb-navbar-links');
if(toggle&&links){toggle.addEventListener('click',function(){links.classList.toggle('open');});}
var sections=document.querySelectorAll('.wb-section[id]');
var navLinks=document.querySelectorAll('.wb-nav-link');
if(sections.length&&navLinks.length){
  var onScroll=function(){var current='';sections.forEach(function(sec){var rect=sec.getBoundingClientRect();if(rect.top<=120&&rect.bottom>120)current=sec.id;});navLinks.forEach(function(link){link.classList.toggle('active',link.getAttribute('href')==='#'+current);});};
  window.addEventListener('scroll',onScroll);onScroll();
}
document.querySelectorAll('.wb-nav-dropdown-trigger').forEach(function(t){
  t.addEventListener('click',function(e){
    if(window.matchMedia('(hover:none)').matches){e.preventDefault();var m=t.nextElementSibling;if(m){var open=m.style.display==='flex';document.querySelectorAll('.wb-nav-dropdown-menu').forEach(function(o){o.style.display='none';});m.style.display=open?'none':'flex';}}
  });
});
document.querySelectorAll('form.wbform[data-wb-mailto]').forEach(function(f){
  f.addEventListener('submit',function(e){
    e.preventDefault();
    var parts=[];
    Array.from(f.elements).forEach(function(el){if(el.name&&el.type!=='submit'){var v=el.type==='checkbox'?(el.checked?'Yes':'No'):el.value;if(v)parts.push(el.name.replace(/^field_/,'')+': '+v);}});
    var body=encodeURIComponent(parts.join('\\n'));
    window.location.href='mailto:?subject='+encodeURIComponent(document.title+' — new form submission')+'&body='+body;
  });
});
var backToTop=document.getElementById('wb-backtotop-btn');
if(backToTop){
  window.addEventListener('scroll',function(){backToTop.classList.toggle('wb-show',window.scrollY>400);});
  backToTop.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});});
}
})();
${Animations.buildJs()}
${window.BgEffects ? BgEffects.exportRuntimeJs() : ''}`;
  },

  buildGoogleFontsUrl(project) {
    const t=project.theme;
    const localNames=new Set((t.localFonts||[]).map(f=>f.name));
    const fams=[...new Set([t.fontHeading,t.fontBody])].filter(f=>!localNames.has(f)).map(f=>f.replace(/ /g,'+')+':400,500,600,700,800').join('&family=');
    return fams?`https://fonts.googleapis.com/css2?family=${fams}&display=swap`:null;
  },

  buildDataMarker(project) {
    const base64=btoa(unescape(encodeURIComponent(JSON.stringify(project))));
    return `<!-- WBP-DATA:${base64} -->`;
  },

  buildFloatingWidgets(project) {
    const ss = project.siteSettings || {};
    const btns = [];
    if (ss.whatsappEnabled && ss.whatsappNumber) {
      btns.push(`<a class="wb-float-btn wb-float-whatsapp" href="https://wa.me/${escapeHtml(ss.whatsappNumber)}" target="_blank" rel="noopener" aria-label="Chat on WhatsApp">💬</a>`);
    }
    if (ss.callEnabled && ss.callNumber) {
      btns.push(`<a class="wb-float-btn wb-float-call" href="tel:${escapeHtml(ss.callNumber)}" aria-label="Call us">📞</a>`);
    }
    if (ss.backToTop) {
      btns.push(`<button class="wb-float-btn wb-float-backtotop" id="wb-backtotop-btn" aria-label="Back to top">↑</button>`);
    }
    return btns.length ? `<div class="wb-float-widgets">${btns.join('')}</div>` : '';
  },

  buildStandardHtml(project) {
    const gFont=this.buildGoogleFontsUrl(project);
    return `<!DOCTYPE html>
<html lang="en">
<head>
${this.buildDataMarker(project)}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(project.meta.title)}</title>
<meta name="description" content="${escapeHtml(project.meta.description)}">
${project.meta.keywords?`<meta name="keywords" content="${escapeHtml(project.meta.keywords)}">`:''
}${project.meta.ogImage?`<meta property="og:image" content="${escapeHtml(project.meta.ogImage)}">`:''
}${project.meta.favicon?`<link rel="icon" href="${escapeHtml(project.meta.favicon)}">`:''
}<meta name="robots" content="${escapeHtml(project.meta.robots||'index, follow')}">
${project.meta.canonical?`<link rel="canonical" href="${escapeHtml(project.meta.canonical)}">`:''
}${gFont?`<link rel="stylesheet" href="${gFont}">`:''
}<link rel="stylesheet" href="css/style.css">
</head>
<body data-wb-quality-setting="${escapeHtml((project.siteSettings&&project.siteSettings.animQuality)||'high')}" data-wb-auto-detect="${project.siteSettings&&project.siteSettings.animAutoDetect===false?'0':'1'}">
${this.buildNavbar(project)}
${this.buildSectionsHtml(project)}
${this.buildFloatingWidgets(project)}
${project.siteSettings&&project.siteSettings.animAllowDisable?`<button id="wb-anim-toggle" type="button">✨ Animations</button>`:''}
<script src="js/script.js"></script>
</body>
</html>`;
  },

  buildBloggerPagePaste(project) {
    const t=project.theme;
    const gFont=this.buildGoogleFontsUrl(project);
    const minCss=`<style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'${t.fontBody}',system-ui,sans-serif;color:${t.text};background:${t.background};line-height:1.6;}h1,h2,h3,h4{font-family:'${t.fontHeading}',system-ui,sans-serif;line-height:1.2;margin-bottom:.5em;}img{max-width:100%;display:block;}a{text-decoration:none;color:inherit;}.wb-container{max-width:${t.container||1140}px;margin:0 auto;padding:0 24px;}.wb-btn{display:inline-block;padding:12px 28px;border-radius:${t.radius!==undefined?t.radius:8}px;font-weight:600;}.wb-btn-primary{background:${t.primary};color:#fff;}.wb-btn-light{background:#fff;color:${t.secondary};}.wb-section{width:100%;}.wb-float-widgets{position:fixed;right:20px;bottom:20px;display:flex;flex-direction:column;gap:12px;z-index:999;}.wb-float-btn{width:56px;height:56px;border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,.25);font-size:1.6rem;text-decoration:none;color:#fff!important;border:none;cursor:pointer;}.wb-float-whatsapp{background:#25d366;}.wb-float-call{background:${t.primary};}.wb-float-backtotop{background:${t.secondary};opacity:0;pointer-events:none;transition:opacity .2s ease;}.wb-float-backtotop.wb-show{opacity:1;pointer-events:auto;}</style>`;
    return `${gFont?`<link rel="stylesheet" href="${gFont}">`:''}\n${minCss}\n${this.buildNavbar(project)}\n${this.buildSectionsHtmlBloggerSafe(project)}\n${this.buildFloatingWidgets(project)}\n<script>\n${this.buildBaseJs()}\n</script>`;
  },

  /**
   * buildBloggerXml — generates a complete Blogger XML theme.
   *
   * KEY XML FIXES applied here:
   * 1. NO <!DOCTYPE html> — Blogger's parser rejects it; Blogger supplies its own
   * 2. htmlForCdata(): escapeHtml() produces &amp; &lt; &gt; etc. Inside CDATA
   *    those are NOT decoded — they render as literal text. We unescape back to
   *    raw chars so image URLs, text, etc. render correctly in the browser.
   * 3. safeCdata(): splits any ]]> sequence that would prematurely close CDATA
   * 4. Google Fonts href uses &amp; — it's an XML attribute, OUTSIDE CDATA
   * 5. No HTML comments with double-dash -- inside (XML spec disallows --)
   * 6. JS in <script> directly in body (not in b:widget) — avoids extra wrapper divs
   * 7. JS wrapped in //<![CDATA[ ... //]]> for XML validity while executing normally
   * 8. <b:skin> is a DIRECT child of <head> — NOT nested inside <b:template-skin>.
   *    Per Blogger's own docs, <b:skin> and <b:template-skin> are separate sibling
   *    tags that cannot be nested; nesting them is what broke "Restore" on Blogger.
   */
  buildBloggerXml(project) {
    const t=project.theme;
    const gFont=this.buildGoogleFontsUrl(project);

    const fullCss=this.buildBaseCss(project);
    const navbarCss=[
      '.wb-navbar{position:sticky;top:0;z-index:100;background:rgba(255,255,255,.95);backdrop-filter:blur(8px);box-shadow:0 1px 0 rgba(0,0,0,.06);}',
      '.wb-navbar-inner{display:flex;align-items:center;justify-content:space-between;height:68px;max-width:1140px;margin:0 auto;padding:0 24px;}',
      '.wb-navbar-brand{font-weight:700;font-size:1.15rem;text-decoration:none;color:inherit;}',
      '.wb-navbar-links{display:flex;gap:28px;}',
      '.wb-nav-link{font-weight:500;font-size:.95rem;text-decoration:none;}',
      `.wb-nav-link.active{color:${t.primary};}`,
      '.wb-navbar-toggle{display:none;background:none;border:none;font-size:1.6rem;cursor:pointer;padding:4px 8px;}',
      '@media(max-width:820px){',
      '.wb-navbar-toggle{display:block;}',
      '.wb-navbar-links{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(10,10,10,.97);flex-direction:column;align-items:center;justify-content:center;gap:32px;display:none;z-index:999;}',
      '.wb-navbar-links.open{display:flex;}',
      '.wb-navbar-links .wb-nav-link{font-size:1.3rem;color:#fff;}',
      '}',
    ].join('\n');

    const combinedCss=fullCss+'\n'+navbarCss;
    const sectionsHtml=this.buildSectionsHtmlBloggerSafe(project);
    const navbarHtml=this.buildNavbar(project);
    const jsContent=this.buildBaseJs();

    // CDATA helpers
    // safeCdata: prevents premature CDATA close if content contains ]]>
    const safeCdata=str=>str.replace(/\]\]>/g,']]]]><![CDATA[>');

    // htmlForCdata: HTML built by escapeHtml() has XML entities (&amp; &lt; etc.)
    // Inside CDATA, XML entity decoding is suspended — &amp; renders literally
    // as &amp; in the browser output. We must convert back to raw chars first.
    const htmlForCdata=str=>str
      .replace(/&amp;/g,'&')
      .replace(/&lt;/g,'<')
      .replace(/&gt;/g,'>')
      .replace(/&quot;/g,'"')
      .replace(/&#039;/g,"'");

    // toCdata: apply both fixes for content going inside CDATA widget settings
    const toCdata=str=>safeCdata(htmlForCdata(str));

    // xa: XML-escape for attribute values OUTSIDE CDATA (e.g. href, title attrs)
    const xa=str=>String(str||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/'/g,'&apos;');

    // Google Fonts URL in XML attribute — & must be &amp;
    const gFontLink=gFont
      ? `  <link href='${gFont.replace(/&/g,'&amp;')}' rel='stylesheet' type='text/css'/>`
      : '';

    return `<?xml version="1.0" encoding="UTF-8" ?>
<html b:css='false' b:defaultwidgetversion='2' b:js='false' b:version='2'
  class='v2' expr:dir='data:blog.languageDirection'
  xmlns='http://www.w3.org/1999/xhtml'
  xmlns:b='http://www.google.com/2005/gml/b'
  xmlns:data='http://www.google.com/2005/gml/data'
  xmlns:expr='http://www.google.com/2005/gml/expr'>
<head>
  <meta charset='utf-8'/>
  <meta content='width=device-width, initial-scale=1' name='viewport'/>
  <b:include data='blog' name='all-head-content'/>
  <title><data:blog.pageTitle/></title>
${gFontLink}
  <b:skin><![CDATA[
/* ${xa(project.meta.title)} - Generated by Offline Website Builder Pro */
${safeCdata(combinedCss)}
  ]]></b:skin>
</head>
<body data-wb-quality-setting='${xa((project.siteSettings&&project.siteSettings.animQuality)||'high')}' data-wb-auto-detect='${project.siteSettings&&project.siteSettings.animAutoDetect===false?'0':'1'}'>
${project.siteSettings&&project.siteSettings.animAllowDisable?`<button id='wb-anim-toggle' type='button'>&#10024; Animations</button>`:''}

<b:section id='wb-nav' class='wb-nav-section' maxwidgets='1' showaddelement='no'>
<b:widget id='HTML1' locked='true' title='Navigation' type='HTML' version='2'>
<b:widget-settings>
<b:widget-setting name='content'><![CDATA[${toCdata(navbarHtml)}]]></b:widget-setting>
</b:widget-settings>
<b:includable id='main'>
<div class='widget-content'><data:content/></div>
</b:includable>
</b:widget>
</b:section>

<b:section id='wb-content' class='wb-content-section' maxwidgets='1' showaddelement='no'>
<b:widget id='HTML2' locked='true' title='Site Content' type='HTML' version='2'>
<b:widget-settings>
<b:widget-setting name='content'><![CDATA[${toCdata(sectionsHtml)}]]></b:widget-setting>
</b:widget-settings>
<b:includable id='main'>
<div class='widget-content'><data:content/></div>
</b:includable>
</b:widget>
</b:section>
${this.buildFloatingWidgets(project) ? `
<b:section id='wb-floating' class='wb-floating-section' maxwidgets='1' showaddelement='no'>
<b:widget id='HTML3' locked='true' title='Floating Widgets' type='HTML' version='2'>
<b:widget-settings>
<b:widget-setting name='content'><![CDATA[${toCdata(this.buildFloatingWidgets(project))}]]></b:widget-setting>
</b:widget-settings>
<b:includable id='main'>
<div class='widget-content'><data:content/></div>
</b:includable>
</b:widget>
</b:section>` : ''}

<script type='text/javascript'>
//<![CDATA[
${safeCdata(jsContent)}
//]]>
</script>

</body>
</html>`;
  },

  slugify(str){return String(str).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'website';},

  downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);},

  downloadBloggerXml(project){
    const xml=this.buildBloggerXml(project);
    const blob=new Blob([xml],{type:'application/xml;charset=utf-8'});
    this.downloadBlob(blob,`${this.slugify(project.meta.title)}-blogger-theme.xml`);
    UI.toast('Blogger XML downloaded. Upload via Blogger > Theme > Restore > Upload','success');
  },

  buildReadme(project){
    const publishedPosts=(project.posts||[]).filter(p=>p.status==='published');
    const hasSitemap=!!(project.siteSettings&&project.siteSettings.siteUrl);
    const hasBgEffects=(project.sections||[]).some(s=>s.bgEffect&&s.bgEffect!=='none');
    const hasScrollAnim=(project.sections||[]).some(s=>s.animation&&s.animation.type&&s.animation.type!=='none');
    return `${project.meta.title} - Exported by Offline Website Builder Pro
=====================================================

FILES IN THIS EXPORT
---------------------
index.html          - Your site's homepage
css/style.css        - All styling, including any animated backgrounds and scroll effects
js/script.js          - Navigation, scroll-reveal, and background-animation runtime (no external libraries)
blogger-theme.xml   - Complete Blogger XML theme
                      Upload: Blogger > Theme > down arrow > Restore > Upload
blogger-page.html   - Paste into a Blogger Page HTML editor (fallback, if you'd rather not replace your whole theme)
${hasSitemap?'sitemap.xml           - Submit this to Google Search Console once your site is live\n':''}${publishedPosts.length?`blog-*.html          - ${publishedPosts.length} published blog post page${publishedPosts.length===1?'':'s'}, one file per post\n`:''}
BLOGGER XML INSTALLATION (Recommended for Blogger)
---------------------------------------------------
1. Blogger Dashboard > Theme
2. Click the down arrow next to Customise
3. Choose Restore > Upload
4. Select blogger-theme.xml
5. Done - your site is live on Blogger

STANDARD HOSTING (Cloudflare Pages / Netlify / GitHub Pages)
--------------------------------------------------------------
Upload all files (keeping the folder structure: css/, js/, and any blog-*.html
pages alongside index.html) to your host of choice. No build step required.

${hasBgEffects?`ANIMATED BACKGROUNDS
---------------------
One or more sections use an animated background (particles, gradients, etc).
These are pure CSS/Canvas — no server, no external libraries. They automatically:
  - simplify or turn off on low-end phones and older laptops
  - pause while the browser tab is in the background
  - respect a visitor's "reduce motion" accessibility setting
Adjust quality (Low/Medium/High/Ultra) under Theme mode > Background Animations
in the builder if the site ever feels heavy on a particular device.

`:''}${hasScrollAnim?`SCROLL REVEAL ANIMATIONS
--------------------------
Sections fade/slide into view as visitors scroll. Turn this off site-wide under
Theme mode > Scroll Reveal Animations in the builder, or override it per-section
in that section's Inspector panel. Always respects "reduce motion" automatically.

`:''}NEED TO MAKE CHANGES LATER?
-----------------------------
Re-open this project in Offline Website Builder Pro using the "Open" button and
your saved .builder project file (💾 Save while you work to create one) — this
carries over everything, including Collections/Forms/Blog content and both
animation systems' settings.

If you don't have the .builder file anymore, use the "⬆ Import" button and
select this index.html itself — your whole project is embedded inside it too.
`;
  },

  async ensureJSZip(){
    if(window.JSZip)return window.JSZip;
    await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='js/vendor/jszip.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('JSZip not found in js/vendor/'));document.head.appendChild(s);});
    return window.JSZip;
  },

  buildBlogPostHtml(project, post) {
    const gFont = this.buildGoogleFontsUrl(project);
    const title = escapeHtml(post.seoTitle || post.title);
    const desc = escapeHtml(post.seoDescription || post.excerpt || '');
    const bodyHtml = escapeHtml(post.body).split(/\n{2,}/).map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`).join('');
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} — ${escapeHtml(project.meta.title)}</title>
<meta name="description" content="${desc}">
${project.meta.favicon ? `<link rel="icon" href="${escapeHtml(project.meta.favicon)}">` : ''}
${gFont ? `<link rel="stylesheet" href="${gFont}">` : ''}
<link rel="stylesheet" href="css/style.css">
</head>
<body>
${this.buildNavbar(project)}
<article class="wb-section" style="padding:64px 0;">
  <div class="wb-container" style="max-width:720px;">
    <div style="font-size:.8rem;opacity:.6;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px;">${escapeHtml(post.category || '')} · ${escapeHtml(post.publishedAt || '')}</div>
    <h1 style="font-size:2.2rem;margin-bottom:20px;">${escapeHtml(post.title)}</h1>
    ${post.featuredImage ? `<img src="${escapeHtml(post.featuredImage)}" alt="${escapeHtml(post.title)}" style="width:100%;border-radius:var(--wb-radius,14px);margin-bottom:28px;">` : ''}
    <div style="font-size:1.05rem;line-height:1.8;">${bodyHtml}</div>
    ${post.tags ? `<div style="margin-top:32px;font-size:.85rem;opacity:.6;">Tags: ${escapeHtml(post.tags)}</div>` : ''}
    ${post.author ? `<div style="margin-top:8px;font-size:.85rem;opacity:.6;">By ${escapeHtml(post.author)}</div>` : ''}
    <a href="index.html" class="wb-btn wb-btn-primary" style="margin-top:32px;display:inline-block;">&larr; Back to home</a>
  </div>
</article>
${this.buildFloatingWidgets(project)}
<script src="js/script.js"></script>
</body>
</html>`;
  },

  buildSitemap(project) {
    const base = (project.siteSettings && project.siteSettings.siteUrl) ? project.siteSettings.siteUrl.replace(/\/$/, '') : '';
    if (!base) return null;
    const urls = [`${base}/index.html`];
    (project.posts || []).filter(p => p.status === 'published').forEach(p => urls.push(`${base}/blog-${p.slug||this.slugify(p.title)}.html`));
    const items = urls.map(u => `  <url><loc>${escapeHtml(u)}</loc></url>`).join('\n');
    return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${items}\n</urlset>`;
  },

  async exportZip(project){
    try{
      const JSZipLib=await this.ensureJSZip();
      const zip=new JSZipLib();
      zip.file('index.html',this.buildStandardHtml(project));
      zip.file('css/style.css',this.buildBaseCss(project));
      zip.file('js/script.js',this.buildBaseJs());
      zip.file('blogger-theme.xml',this.buildBloggerXml(project));
      zip.file('blogger-page.html',this.buildBloggerPagePaste(project));
      zip.file('README.txt',this.buildReadme(project));
      const publishedPosts=(project.posts||[]).filter(p=>p.status==='published');
      publishedPosts.forEach(p=>{ zip.file(`blog-${p.slug||this.slugify(p.title)}.html`, this.buildBlogPostHtml(project,p)); });
      const sitemap=this.buildSitemap(project);
      if(sitemap) zip.file('sitemap.xml',sitemap);
      const blob=await zip.generateAsync({type:'blob'});
      this.downloadBlob(blob,`${this.slugify(project.meta.title)}.zip`);
      UI.toast('Export complete','success');
    }catch(err){UI.toast('Export failed: '+err.message,true);}
  },
};
window.Exporter=Exporter;
